[metadata]
name = "audio-video"
description = "A channel to select files for mpv"
requirements = ["fd"]

[source]
command = "fd --extension mp4 --extension mp3 --extension webm --extension mov --extension mkv --extension flac --extension m4a --extension m4v"

